version: '3.9'

services:
  database:
    image: postgres
    container_name: ngcashdatabasecontainer
    restart: always
    # port:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ngdatabase
    volumes: 
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
